---
title: "ready4class"
author: "Matthew Hamilton"
date: "`r format.Date(Sys.Date(),'%B %d, %Y')`"
output: 
  html_document:
    theme: journal
---
ready4fun is a toolkit to streamline the creation and extension of classes for use with the  [readyforwhatsnext](https://readyforwhatsnext.github.io/readyforwhatsnext/index.html) replicable mental health simulations suite. A version of the ready4class package that is currently being tested is available at: https://github.com/readyforwhatsnext/ready4class

There are two versions of the package manual currently available. A slimmed down manual, which includes details of only the functions that are relevant to the majority of intended users is available at:
https://readyforwhatsnext.github.io/readyforwhatsnext/pdfs/ready4class_0.0.0.9119.pdf

For those undertaking testing of the code library or who may write code that extends the functions in ready4class, there is a more detailed manual that specifies the helper functions that most users will never need to see. That more detailed manual is available at:
https://readyforwhatsnext.github.io/readyforwhatsnext/pdfs/ready4class_0.0.0.9119_dev.pdf

Please note that the current documentation is extremely rudimentary and no vignettes are currently developed. Expanded documentation will be provided in the release version of the code library.
